typography_spectrum: 0.7608252726495266
color:
  brandStrength: 0.798877312336117
  lightness: 0.9057517684996128
  saturation: 0.828455438837409
  rhythmicContrast: 0.12036954355426133
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.8784160013310611
author:
  name: Penelope Stetz
  email: Coach@PenelopeStetz.com
  url: 'http://PenelopeStetz.com'
name: PenelopeStetz.com
title: Law of Attraction Coach
